title: Hwang's Blog
email: hsb990105@gmail.com
description: >-
  Development & Study Blog

baseurl: ""
url: "https://hwangsb.github.io"
github_username: HwangSB

# Author information
author:
  name: Hwang SangBeom
  email: hsb990105@gmail.com
  github: HwangSB

# Site settings
lang: ko-KR
timezone: Asia/Seoul

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/category/:name/'
    tag: '/tag/:name/'

# SEO and social
social:
  name: Hwang SangBeom
  links:
    - https://github.com/HwangSB

# Minima theme settings
minima:
  date_format: "%Y년 %m월 %d일"
  social_links:
    github: HwangSB
    rss: rss

# Navigation menu
header_pages:
  - about.md
  - categories.html
  - tags.html

# Show excerpts on homepage
show_excerpts: true
